### PR TITLE
Resolve values from completed tracer/runner contexts

### LINKED ISSUE #104: Cannot use proxy values from previous runs with `remote=True`
### Description
I noticed a discrepancy between `remote=False` and `remote=True` behavior when re-using a proxy from a previous run.

When `remote=False`, I can reuse the previous proxy in a previous tracer/generator context, but it's not possible with `remote=True`.

### Expected Behavior
The behavior should be the same whether remote is True or False.

### Reproduction Steps
```python
from nnsight import CONFIG, LanguageModel

CONFIG.set_default_api_key("<your-api-key>")
model = LanguageModel('openai-community/gpt2-xl')

def run(remote: bool):    
    with model.generate("a dog is a dog, a cat is", max_new_tokens=4, remote=remote):
        embedding = model.transformer.wte.output.save()
        output1 = model.generator.output.save()
    
    print(embedding.shape)
    print("All token ids: ", output1)
    print("All prediction: ", model.tokenizer.batch_decode(output1))
    
    tokens_cnt = embedding.shape[1]
    stub_prompt = " ".join("_" * tokens_cnt)
    with model.generate(stub_prompt, max_new_tokens=4, remote=remote):
        model.transformer.wte.output = embedding
        output2 = model.generator.output.save()

    print("All token ids: ", output2)
    print("All prediction: ", model.tokenizer.batch_decode(output2))
```

`run(False)` output:
```
torch.Size([1, 9, 1600])
All token ids:  tensor([[  64, 3290,  318,  257, 3290,   11,  257, 3797,  318,  257, 3797,   11,
          290]])
All prediction:  ['a dog is a dog, a cat is a cat, and']

All token ids:  tensor([[  62, 4808, 4808, 4808, 4808, 4808, 4808, 4808, 4808,  257, 3797,   11,
          290]])
All prediction:  ['_ _ _ _ _ _ _ _ _ a cat, and']
```

`run(True)` output:
```
torch.Size([1, 9, 1600])
All token ids:  tensor([[  64, 3290,  318,  257, 3290,   11,  257, 3797,  318,  257, 3797,   11,
          290]])
All prediction:  ['a dog is a dog, a cat is a cat, and']

All token ids:  tensor([[  62, 4808, 4808, 4808, 4808, 4808, 4808, 4808, 4808, 4808, 4808, 4808,
         4808]])
All prediction:  ['_ _ _ _ _ _ _ _ _ _ _ _ _']
```

### PR DESCRIPTION
**Pull request by tvhong**
### Notes
Fixing #104.

### Testing
~~I haven't tested this with `remote=True` yet because the NDIF server is unavailable at the moment. I'll run the test in #104 with `remote=True` when it's back up online.~~

Confirmed that it fixed the problem described in #104 

Output of `run(remote=True)`:
```
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

661888c6bc19a1bcb53ea1c0 - RECEIVED: Your job has been received and is waiting approval.
661888c6bc19a1bcb53ea1c0 - APPROVED: Your job was approved and is waiting to be run.
661888c6bc19a1bcb53ea1c0 - COMPLETED: Your job has been completed.

Downloading result:   0%|                                      | 0.00[/59.2k](http://localhost:8888/59.2k) [00:00<?, ?B[/s](http://localhost:8888/s)]huggingface[/tokenizers](http://localhost:8888/tokenizers): The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Downloading result: 100%|██████████████████████████████| 59.2k[/59.2k](http://localhost:8888/59.2k) [00:00<00:00, 472kB[/s](http://localhost:8888/s)]
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

torch.Size([1, 9, 1600])
All token ids:  tensor([[  64, 3290,  318,  257, 3290,   11,  257, 3797,  318,  257, 3797,   11,
          290]])
All prediction:  ['a dog is a dog, a cat is a cat, and']
661888ca637e36f9660fa6b4 - RECEIVED: Your job has been received and is waiting approval.
661888ca637e36f9660fa6b4 - APPROVED: Your job was approved and is waiting to be run.
661888ca637e36f9660fa6b4 - COMPLETED: Your job has been completed.

Downloading result: 100%|█████████████████████████████| 1.31k[/1.31k](http://localhost:8888/1.31k) [00:00<00:00, 3.33MB[/s](http://localhost:8888/s)]

All token ids:  tensor([[  62, 4808, 4808, 4808, 4808, 4808, 4808, 4808, 4808,  257, 3797,   11,
          290]])
All prediction:  ['_ _ _ _ _ _ _ _ _ a cat, and']
```

### CODE REVIEW

**Comment by JadenFiotto-Kaufman** [comment]
@tvhong  This is a great solution! I think instead I would just have Node arguments that are Nodes check if they are .done() and convert them to their value if so. Something like `args = util.apply(args, lambda x : x.value if x.done() else x, Node)` in tracing.Node.Node.__init__ . Could you make that change and then I'll merge it in? 

Also in the solution you have now, you have `TensorModel(values=value.value.tolist(), dtype=str(value.value.dtype).split(".")[-1])` , but the node could have any number of different data types instead of a Tensor right, so this would only work if it happened to be a Tensor.

**Comment by tvhong** [comment]
@JadenFiotto-Kaufman Thank you for the pointer! I have updated the code following your hint. I'll test it again once the NDIF server is back up online.

And, yes, I didn't realize `.value` can be of other types apart from Tensor. Just for my education, when would `.value` not be a tensor?

**Comment by JadenFiotto-Kaufman** [comment]
@tvhong NDIF should be back up 👍. The inputs and outputs of modules are often not just tensors. The most common examples being tuples, lists and dictionaries. But they could be anything. Like gpt for example, the final output of the model is some object like GPTCausalModelOutput.

**Comment by tvhong** [comment]
Tested this change with `run(remote=True)`. Confirm that it fixes the issue described in #104.

**Pull request merged**
